# Generated by Django 2.1.7 on 2019-12-30 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CHANGE',
            fields=[
                ('ID', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='记录号')),
                ('DESCRIPTION', models.TextField(verbose_name='描述')),
            ],
            options={
                'verbose_name_plural': '学籍变更记录',
                'verbose_name': '学籍变更',
                'db_table': 'CHANGE',
            },
        ),
        migrations.CreateModel(
            name='CHANGE_CODE',
            fields=[
                ('CODE', models.BooleanField(primary_key=True, serialize=False, verbose_name='代码')),
                ('DESCRIPTION', models.CharField(max_length=10, verbose_name='描述')),
            ],
            options={
                'verbose_name_plural': '学籍变动代码表',
                'verbose_name': '学籍变动代码',
                'db_table': 'CHANGE_CODE',
            },
        ),
        migrations.CreateModel(
            name='CLASS',
            fields=[
                ('ID', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='班级编号')),
                ('NAME_CLA', models.CharField(max_length=50, verbose_name='全称')),
            ],
            options={
                'verbose_name_plural': '班级信息表',
                'verbose_name': '班级',
                'db_table': 'CLASS',
            },
        ),
        migrations.CreateModel(
            name='DEPARTMENT',
            fields=[
                ('ID', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='学院编号')),
                ('NAME_DEP', models.CharField(max_length=50, verbose_name='全称')),
            ],
            options={
                'verbose_name_plural': '院系信息表',
                'verbose_name': '院系',
                'db_table': 'DEPARTMENT',
            },
        ),
        migrations.CreateModel(
            name='PUNISH',
            fields=[
                ('ID', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='记录号')),
                ('ENABLE', models.BooleanField(choices=[('1', 'T'), ('0', 'F')], verbose_name='是否生效')),
                ('REC_TIME', models.DateField(verbose_name='记录时间')),
                ('DESCRIPTION', models.TextField(verbose_name='描述')),
            ],
            options={
                'verbose_name_plural': '处罚记录代码表',
                'verbose_name': '处罚记录',
                'db_table': 'PUNISH',
            },
        ),
        migrations.CreateModel(
            name='PUNISH_LEVELS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LEVELS', models.BooleanField(verbose_name='级别')),
                ('DESCRIPTION', models.CharField(max_length=10, verbose_name='描述')),
            ],
            options={
                'verbose_name_plural': '处罚级别代码表',
                'verbose_name': '处罚级别',
                'db_table': 'PUNISH_LEVELS',
            },
        ),
        migrations.CreateModel(
            name='REWARD',
            fields=[
                ('ID', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='记录号')),
                ('REC_TIME', models.DateField(verbose_name='记录时间')),
                ('DESCRIPTION', models.TextField(verbose_name='描述')),
            ],
            options={
                'verbose_name_plural': '奖励记录',
                'verbose_name': '奖励记录',
                'db_table': 'REWARD',
            },
        ),
        migrations.CreateModel(
            name='REWARD_LEVELS',
            fields=[
                ('LEVELS', models.BooleanField(primary_key=True, serialize=False, verbose_name='级别')),
                ('DESCRIPTION', models.CharField(max_length=10, verbose_name='描述')),
            ],
            options={
                'verbose_name_plural': '奖励级别表',
                'verbose_name': '奖励级别',
                'db_table': 'REWARD_LEVELS',
            },
        ),
        migrations.CreateModel(
            name='STUDENT',
            fields=[
                ('STUDENTID', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='学号')),
                ('NAME_STU', models.CharField(max_length=10, verbose_name='姓名')),
                ('SEX', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=1, verbose_name='性别')),
                ('BIRTHDAY', models.DateField(verbose_name='生日')),
                ('NATIVE_PLACE', models.CharField(max_length=50, verbose_name='籍贯')),
                ('NAME_CLA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.CLASS', verbose_name='班级')),
                ('NAME_DEP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.DEPARTMENT', verbose_name='院系')),
            ],
            options={
                'verbose_name_plural': '学生个人信息表',
                'verbose_name': '学生',
                'db_table': 'STUDENT',
            },
        ),
        migrations.AddField(
            model_name='reward',
            name='LEVELS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.REWARD_LEVELS', verbose_name='级别代码'),
        ),
        migrations.AddField(
            model_name='reward',
            name='STUDENTID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.STUDENT', verbose_name='学号'),
        ),
        migrations.AddField(
            model_name='punish',
            name='LEVELS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.PUNISH_LEVELS', verbose_name='级别代码'),
        ),
        migrations.AddField(
            model_name='punish',
            name='STUDENTID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.STUDENT', verbose_name='学号'),
        ),
        migrations.AddField(
            model_name='change',
            name='CODE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.CHANGE_CODE', verbose_name='变更代码'),
        ),
        migrations.AddField(
            model_name='change',
            name='STUDENTID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.STUDENT', verbose_name='学号'),
        ),
    ]
