# Generated by Django 2.1.7 on 2019-12-30 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='punish',
            options={'verbose_name': '处罚记录', 'verbose_name_plural': '处罚记录'},
        ),
        migrations.AlterField(
            model_name='student',
            name='NAME_CLA',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.CLASS', verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='student',
            name='NAME_DEP',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.DEPARTMENT', verbose_name='院系'),
        ),
    ]
