# Generated by Django 2.1.7 on 2019-12-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20191230_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='NAME_CLA',
            field=models.CharField(max_length=50, null=True, verbose_name='全称'),
        ),
        migrations.AlterField(
            model_name='department',
            name='NAME_DEP',
            field=models.CharField(max_length=50, null=True, verbose_name='全称'),
        ),
    ]
