# Generated by Django 2.1.7 on 2019-12-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20191230_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='PASSWORD',
            field=models.CharField(default='123456', max_length=20, verbose_name='密码'),
        ),
    ]
