# Generated by Django 2.1.7 on 2020-01-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change_code',
            name='CODE',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='代码'),
        ),
        migrations.AlterField(
            model_name='punish_levels',
            name='LEVELS',
            field=models.IntegerField(verbose_name='级别'),
        ),
        migrations.AlterField(
            model_name='reward_levels',
            name='LEVELS',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='级别'),
        ),
    ]
