# Generated by Django 2.1.7 on 2020-01-02 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20200102_0902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='change_code',
            options={'verbose_name': '学籍变动', 'verbose_name_plural': '学籍变动代码表'},
        ),
    ]
